version: "3.8"
name: piscine-ds

services:
  db:
    image: postgres:16.3
    volumes:
      - ${GOINFRE_PATH}/postgresql:/var/lib/postgresql/data
      - ${GOINFRE_PATH}/raw_data:/var/lib/postgresql/raw_data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 5s
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.9
    volumes:
      - ./pgpass:/pgpass
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 8080:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
