version: "3.8"
name: piscine-ds

services:
  db:
    image: postgres:16.3
    volumes:
      - ${GOINFRE_PATH}/postgresql:/var/lib/postgresql/data
      - ${GOINFRE_PATH}/raw_data:/var/lib/postgresql/raw_data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 5s
