version: "3.8"
name: piscine-ds

services:
  db:
    image: postgres:15.3
    volumes:
      - db-data:/var/lib/postgresql/data
      - /goinfre/sunpark:/var/lib/postgresql/goinfre
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: sunpark
      POSTGRES_DB: piscineds
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 5s
